name: publish

on: push

jobs:

  prebuild:
    name: test, lint, and type check
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Set up environment
        run: >-
          pip install .[dev]
      - name: Test with pytest
        run: >-
          pytest -W error
      - name: Lint with ruff
        run: >-
          ruff check aqua_blue/
      - name: Type check with mypy
        run: >-
          mypy aqua_blue/

  quickstart:
    name: run quickstart
    runs-on: ubuntu-latest
    permissions:
      content: read

    steps:
      - uses: actions/checkout@v4
          with:
            persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Set up non-developer environment
        run: >-
          pip install .
      - name: Extract quickstart from README.md
        run: >-
          awk '/```py/,/```/' README.md | sed '1d;$d' > _quickstart.py
      - name: Run quickstart script
        run: >-
          python _quickstart.py

  build:
    needs:
      - prebuild
    name: build distribution
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  pypi-publish:
    needs:
      - build
    name: upload release to PyPI
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/aqua-blue
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
